=== hZambrzycki/XML-XSD-XSLT/Exercise17/XSD_EJ3.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="supermercado">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="medida" type="xs:string"/>
                            <xs:element name="seccion" type="xs:string"/>
                            <xs:element name="oferta" type="xs:string" minOccurs="0"/>
                            <xs:choice>
                                 <xs:element name="perecedero" type="xs:string">
                             <xs:complexType>
                                
                               <xs:all>
                                 <xs:element name="fabricacion" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                                                    
                                 </xs:element>
                                    </xs:all>
                                </xs:complexType>
                       
                        
                          
                            
                       
                                                                    

                            </xs:element>
                            </xs:choice>
                        </xs:sequence>
                        </xs:complexType>
                        </xs:element>
                        </xs:sequence>
                        </xs:complexType>
    </xs:element>

</xs:schema>

=== hZambrzycki/XML-XSD-XSLT/Exercise17/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<supermercado
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='XSD_EJ3.xsd'>
    <articulo>
        <descripcion></descripcion>
        <marca></marca>
        <medida></medida>
        <seccion></seccion>
        <oferta></oferta>
        <perecedero></perecedero>
    </articulo>
    <articulo>
        <descripcion></descripcion>
        <marca></marca>
        <medida></medida>
        <seccion></seccion>
        <oferta></oferta>
        <perecedero></perecedero>
    </articulo>
    <articulo>
        <descripcion></descripcion>
        <marca></marca>
        <medida></medida>
        <seccion></seccion>
        <oferta></oferta>
        <perecedero></perecedero>
    </articulo>

</supermercado>
