=== hZambrzycki/XML-XSD-XSLT/Exercise20/XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="fechanacimiento" type="xs:date"/>
                            <xs:element name="numerodocumento" type="xs:int"/>
                            <xs:conplex>
                                <xs:sequence>
                                    
                                </xs:sequence>
                            </xs:conplex>
                            
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hZambrzycki/XML-XSD-XSLT/Exercise21/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<persona
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='XSD.xsd'>
    <nombre>Alejandro</nombre>
    <nombre>Martin</nombre>
  
    <apellido>Perez</apellido>
    <apellido>Sotelo</apellido>
    <!--FORMATO DATE AÃ‘O/MES/DIA -->
    <fechanacimiento>2000-09-24</fechanacimiento>
    <numerodocumento>1111111</numerodocumento>
    <trianero>1</trianero>

</persona>

=== hZambrzycki/XML-XSD-XSLT/Exercise20/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<personas
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='XSD.xsd'>
    <persona>
        <nombre>Antonio</nombre>
        <apellido>Garrido</apellido>
        <fechanacimiento>2000-02-10</fechanacimiento>
        <numerodocumento>21212121</numerodocumento>
        <trianero>0</trianero>
    </persona>
    <persona>
        <nombre>Martin</nombre>
        <apellido>Perez</apellido>
        <fechanacimiento>2000-01-24</fechanacimiento>
        <numerodocumento>41141</numerodocumento>
        <trianero>1</trianero>
    </persona>
    <persona>
        <nombre>Ivan</nombre>
        <apellido>Lopez</apellido>
        <fechanacimiento>1991-12-23</fechanacimiento>
        <numerodocumento>2341211</numerodocumento>
        <trianero>0</trianero>
    </persona>

</personas>
