=== hZambrzycki/XML-XSD-XSLT/Exercise05/EJERCICIO_4.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:attribute name="barrio" type="xs:string" />
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                 
                <xs:element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                       
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="fechanacimiento" type="xs:date"/>
                            <xs:element name="numerodocumento" type="xs:int"/>
                                      
                            <xs:element name="trianero" >

                            <xs:complexType>
                               
                                    <xs:simpleContent>
                                        
                                    <xs:extension base="xs:boolean" >
                                    <xs:attribute name="barrio" type="xs:string" use="required"/>
                                    </xs:extension>
                                    
                                </xs:simpleContent>
                                
                              
                            </xs:complexType>
                              
                              
                            </xs:element>
                           
                        </xs:sequence>
                        <xs:attribute name="puntuacion" type="xs:double"/>     
     
                    </xs:complexType>
                    
                
                </xs:element>
                  
            </xs:sequence>

        </xs:complexType>
          
    </xs:element>
</xs:schema>

=== hZambrzycki/XML-XSD-XSLT/Exercise05/XML_EJERCICIO_$.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<personas
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='EJERCICIO_4.xsd'>
    <persona puntuacion="23">
        <nombre>Antonio</nombre>
        <apellido>Garrido</apellido>
        <fechanacimiento>2000-02-10</fechanacimiento>
        <numerodocumento>21212121</numerodocumento>
        <trianero barrio="Zarzaquemada">1</trianero>
    </persona>
    <persona puntuacion="13">
        <nombre>Martin</nombre>
        <apellido>Perez</apellido>
        <fechanacimiento>2000-01-24</fechanacimiento>
        <numerodocumento>41141</numerodocumento>
        <trianero barrio="Leganes">0</trianero>
    </persona>
    <persona puntuacion="14">
        <nombre>Ivan</nombre>
        <apellido>Lopez</apellido>
        <fechanacimiento>1991-12-23</fechanacimiento>
        <numerodocumento>2341211</numerodocumento>
        <trianero barrio="Aluche">1</trianero>
    </persona>

</personas>
